site_name: TCLB Reference Manual
theme:
  name: 'material'
markdown_extensions:
    - fenced_code
    - codehilite
    - mdx_math
extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
